# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
sudo: false

git:
  depth: 2

cache:
  pip: true

branches:
  only:
    - master
    - devel
    - "/v\\d+\\.\\d+/"

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.5
      env:
        - TOXENV=flake8
    - os: linux
      python: 2.7
      env:
        - TOXENV=py27
    - os: linux
      python: 3.4
      env:
        - TOXENV=py34
    - os: linux
      python: 3.5
      env:
        - TOXENV=py35
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36
    - os: osx
      language: generic
      env:
        - TOXENV=py27
    - os: osx
      language: generic
      env:
        - TOXENV=py36


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - cd geckopy
  - make copy-models
  - bash ci/travis/setup.sh

# command to run tests
script:
  - travis_wait tox -e "${TOXENV}"

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: BenjaSanchez
  password:
    secure: H1li+gCx9qNtce6K+na/vmeePcwLnatNYoP+VHzMHI76Pe9Pa11Og+CIpS8ysFUlZhw1QPW76cn8lUS6DuJ1I/rm3Qz5FpxjAkSTJe36C/6LL9+f7wyKTw3ntZ2Cfj77jIqG0Yr8M+vfF0lqeVsNex+siWSH29waW6YEmNNzY5KvU1WQnUzs+I8ePLBmQ+2kJ9MZw0SBifGqvs8wQCeNf+Kl1BgZLIf0UgX2ueVZHuYWXgxawVMq2zFcyFzRtAZQKO1KClpjk0hb8h+xngEjr8U/YoAVnf41m09QWnljGcD8dpGcP1sHxdwMVUBgyJQlVv6GoWS5od4Ux8j10asmnmfaY35V3mjOXLXnWLk2Q4dl70eKmx1HQ3pCVUG9NrZgUWzIYSepXtx3nEShLZ1iSIjnmqct5cOv6LaRrbMzFNMMQWM/Y1A8+iG58nH865ESlKvwgFTe5eh8OuwSgHmogo5nR1np95UzWWZ5BTGy90JJi/6bLSXuuHOlteoznyZ7SYdolnnlif3bEn5oUQgkZJ4pZZI5lpmWdaKXXByPsD9fj+ipMLk0cxXTW/7KCSJo7MNhHFPvqr/lY1UWfc1jUHFqK41efn9yBcC6Lm5nO9kNcuh9hPzpoDnGhuE8eMeV52qOUeBDNmD1cPMV/tD6pZBf/RitsgOO28cbxGcud38=
  on:
    tags: true
    branch: master
    repo: SysBioChalmers/GECKO
    condition: $TRAVIS_PYTHON_VERSION == "3.6"